import {
    PiPuzzlePieceDuotone,
    PiSwatchesDuotone,
    PiChatDotsDuotone,
    PiDesktopDuotone,
    PiFileTextDuotone,
    PiCompassDuotone,
    PiChartPieSliceDuotone,
    PiUsersDuotone,
    PiShoppingCartDuotone,
    PiCalendarDuotone,
    PiFolderOpenDuotone,
    PiUserCircleDuotone,
    PiChatCircleDuotone,
    PiShoppingCartSimpleDuotone,
    PiLightbulbDuotone,
    PiImagesDuotone,
    PiCalendarCheckDuotone,
    PiWarningDuotone,
    PiGearDuotone,
    PiUserGearDuotone,
    PiCursorClickDuotone,
    PiGridFourDuotone,
    PiTextAaDuotone,
    PiHandWithdrawDuotone,
    PiSpinnerGapDuotone,
    PiBoneDuotone,
    PiSpinnerBallDuotone,
    PiBreadDuotone,
    PiMedalDuotone,
    PiCardsDuotone,
    PiTableDuotone,
    PiTagDuotone,
    PiClockCountdownDuotone,
    PiChatCenteredDuotone,
    PiCheckSquareDuotone,
    PiClipboardTextDuotone,
    PiRowsDuotone,
    PiRowsPlusBottomDuotone,
    PiRadioButtonDuotone,
    PiChartDonutDuotone,
    PiListChecksBold,
    PiToggleRightDuotone,
    PiClockAfternoonDuotone,
    PiUploadDuotone,
    PiCaretCircleDownDuotone,
    PiListDuotone,
    PiCodeSimpleDuotone,
    PiFootprintsDuotone,
    PiBrowsersDuotone,
    PiChartLineUpDuotone,
    PiMapTrifoldDuotone,
    PiCodeDuotone,
    PiDotsThreeCircleDuotone,
    PiCircleHalfTiltDuotone,
    PiHouseLineDuotone,
    PiUserSquare,
} from 'react-icons/pi'

import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    uiComponents: <PiPuzzlePieceDuotone />,
    common: <PiSwatchesDuotone />,
    uiCommonButton: <PiCursorClickDuotone />,
    uiCommonGrid: <PiGridFourDuotone />,
    uiCommonTypography: <PiTextAaDuotone />,
    uiCommonIcons: <PiImagesDuotone />,
    feedback: <PiChatDotsDuotone />,
    uiFeedbackAlert: <PiWarningDuotone />,
    uiFeedbackDialog: <PiChatCircleDuotone />,
    uiFeedbackDrawer: <PiHandWithdrawDuotone />,
    uiFeedbackProgress: <PiSpinnerGapDuotone />,
    uiFeedbackSkeleton: <PiBoneDuotone />,
    uiFeedbackSpinner: <PiSpinnerBallDuotone />,
    uiFeedbackToast: <PiBreadDuotone />,
    dataDisplay: <PiDesktopDuotone />,
    uiDataDisplayAvatar: <PiUserCircleDuotone />,
    uiDataDisplayBadge: <PiMedalDuotone />,
    uiDataDisplayCalendar: <PiCalendarDuotone />,
    uiDataDisplayCard: <PiCardsDuotone />,
    uiDataDisplayTable: <PiTableDuotone />,
    uiDataDisplayTag: <PiTagDuotone />,
    uiDataDisplayTimeline: <PiClockCountdownDuotone />,
    uiDataDisplayTooltip: <PiChatCenteredDuotone />,
    forms: <PiFileTextDuotone />,
    uiFormsCheckbox: <PiCheckSquareDuotone />,
    uiFormsDatepicker: <PiCalendarCheckDuotone />,
    uiFormsFormControl: <PiClipboardTextDuotone />,
    uiFormsInput: <PiRowsDuotone />,
    uiFormsInputGroup: <PiRowsPlusBottomDuotone />,
    uiFormsRadio: <PiRadioButtonDuotone />,
    uiFormsSegment: <PiChartDonutDuotone />,
    uiFormsSelect: <PiListChecksBold />,
    uiFormsSwitcher: <PiToggleRightDuotone />,
    uiFormsTimePicker: <PiClockAfternoonDuotone />,
    uiFormsUpload: <PiUploadDuotone />,
    navigation: <PiCompassDuotone />,
    uiNavigationDropdown: <PiCaretCircleDownDuotone />,
    uiNavigationMenu: <PiListDuotone />,
    uiNavigationPagination: <PiCodeSimpleDuotone />,
    uiNavigationSteps: <PiFootprintsDuotone />,
    uiNavigationTabs: <PiBrowsersDuotone />,
    graph: <PiChartPieSliceDuotone />,
    uiGraphChart: <PiChartLineUpDuotone />,
    uiGraphMaps: <PiMapTrifoldDuotone />,
    concepts: <PiLightbulbDuotone />,
    trainers: <PiUserSquare />,
    users: <PiUsersDuotone />,
    bookings: <PiShoppingCartDuotone />,
    calendar: <PiCalendarDuotone />,
    account: <PiUserCircleDuotone />,
    accountSettings: <PiGearDuotone />,
    accountActivityLogs: <PiFileTextDuotone />,
    accountRoleAndPermission: <PiUserGearDuotone />,
    dashboardEcommerce: <PiShoppingCartSimpleDuotone />,
    others: <PiDotsThreeCircleDuotone />,
    accessDenied: <PiCircleHalfTiltDuotone />,
    landing: <PiHouseLineDuotone />,
    changeLog: <PiCodeDuotone />,
}

export default navigationIcon
